models.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    task = db.Column(db.String(200), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    status = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return f"<Task {self.task}>"

app.py
from flask import Flask
from views import views
from models import db
from dotenv import load_dotenv

app = Flask(__name__)
load_dotenv()

# Config SQL
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///tasks.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)

app.register_blueprint(views)

with app.app_context():
    db.create_all()

if __name__ == '__main__':
    app.run(debug=True)

views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask import flash
from models import Task, db

views = Blueprint('views', __name__)

@views.route('/')
def home():
    tasks = Task.query.order_by(Task.created_at.desc()).all()
    return render_template('index.html', tasks=tasks)

@views.route('/create', methods=['POST', 'GET'])
def create():
    if request.method == 'POST':
        task = request.form['task']
        new_task = Task(task=task)
        db.session.add(new_task)
        db.session.commit()
        flash('New task created successfully!', 'success') 
        return redirect(url_for('views.home'))
    return redirect(url_for('views.home'))

@views.route('/edit/<int:task_id>', methods=['POST', 'GET'])
def edit(task_id):
    task = Task.query.get_or_404(task_id)
    if request.method == 'POST':
        new_task = request.form['task']
        status = request.form.get('status') == 'on'

        if new_task:
            task.task = new_task
            task.status = status
            db.session.commit()
            flash(f'#{task_id} Task Updated Successfully!', 'success')
            return redirect(url_for('views.home'))
    return render_template('edit.html', task=task)

@views.route('/delete/<int:task_id>', methods=['POST'])
def delete(task_id):
    task = Task.query.get_or_404(task_id)
    if request.method == 'POST':
        db.session.delete(task)
        db.session.commit()
        flash(f'#{task_id} Deleted Successfully!', 'wrong')
        return redirect(url_for('views.home'))
    return redirect(url_for('views.home'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>

    {% include 'message.html' %}
    
    {% block content %}
    {% endblock %}

</body>
</html>

templates/edit.html
{% extends 'base.html' %}

{% block title %}
Edit
{% endblock %}

{% block content %}

<div class="body">
    <h1 class="title"> Todo App</h1>

    <div class="form-div">
        <form action="{{ url_for('views.edit', task_id=task.id) }}" method="POST" class="form">
            <label for="task">Edit Task</label>
            <input type="text" name="task" id="task" value="{{ task.task }}">
            <label>
                <input type="checkbox" name="status" {% if task.status %}checked{% endif %}>
                Mark as Completed
            </label>
            <input type="submit" value="Update">
        </form>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}

<div class="body">
    <h1 class="title">Todo App</h1>

    <div class="form-div">
        <form action="{{ url_for('views.create') }}" method="POST" class="form">
            <label for="task">Create Task</label>
            <input type="text" name="task" id="task">
            <input type="submit" value="Create">
        </form>
    </div>
    
    <div class="cards-body">
        {% if tasks %}
            {% for task in tasks %}
                <div class="card">
                    <div class="data">
                        <h3><span>#{{ task.id }}</span> {{ task.task }}</h3>
                        <p class="light-text">{{ task.created_at.strftime('%d, %B %Y') }}</p>
                    </div>
                    <div class="btns">
                        <div>
                            {% if task.status == True %}
                                <p class="done">✔️Complete</p>
                            {% else %}
                                <p class="undone">❌Pending</p>
                            {% endif %}
                        </div>
                        <a href="{{ url_for('views.edit', task_id=task.id) }}">
                            <button class="edit">Edit</button>
                        </a>
                        <form action="{{ url_for('views.delete', task_id=task.id) }}" method="POST">
                            <button type="submit" onclick="return confirm('Are you sure?')" class="delete">Delete</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No tasks available.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/message.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="flash-message {{ category }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}